version: '3.9'

services:
  payments_web:
    container_name: web_payments_hive
    image: payments_hive:latest
    command: python main.py
    ports:
      - 9090:9090
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    container_name: redis_payment_hive
    image: redis/redis-stack:latest
    
    volumes:
      - ./redis/data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  redis_data:
